### ISSUE TITLE
etcd Auth Not Supported

### ISSUE THREAD

**Issue by ChrisJones75** [linkorb/etcd-php#12]
Thanks for creating this library, it's pretty close to exactly what we need. Unfortunately, after reviewing the documentation and code, it appears that authentication to etcd is not supported by this client. Guzzle supports basic auth (http://docs.guzzlephp.org/en/5.3/clients.html#auth), but it doesn't look like this can be passed into the Client class. 

Is this something on your roadmap or is there a work around that you suggest?

**Comment by joostfaassen** [comment]
Hi @ChrisJones75, you're right, that's not possible with the latest version.
but: it could be easily supported by allowing the caller to pass in a pre-configured Guzzle client instance (with basic auth configured) into either the constructor or a setter.
I currently don't have the option to work on that, but a PR is very welcome!

**Comment by ChrisJones75** [comment]
Thanks for the quick response @joostfaassen. I'll check into the modifications and submit a PR if I can figure it out.

**Comment by joostfaassen** [comment]
Just merged #22 solving this issue.
